### ISSUE TITLE
NC 13 RC1: Activity-notification mail not sent: Swift_RfcComplianceException

### ISSUE THREAD

**Issue by umgfoin** [nextcloud/activity#239]
### Steps to reproduce
1. Enable notifications and set schedule to "as soon as possible"
2. Create public shared file
3. Download file via public link
4. Wait for notification-mail or check maillog

### Expected behaviour
Activity email to be received for each download

### Actual behaviour
Email not sent - nextcloud log shows RFC-compliance-failure
refer log below

## Server configuration detail

**Operating system:** Linux 2.6.32-042stab120.20 #1 SMP Fri Mar 10 16:52:50 MSK 2017 x86_64

**Webserver:** nginx/1.11.10 (fpm-fcgi)

**Database:** pgsql PostgreSQL 10.1 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18), 64-bit

**PHP version:** 7.1.13
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, SPL, iconv, Reflection, session, standard, SimpleXML, sockets, mbstring, tokenizer, xml, cgi-fcgi, mysqlnd, apcu, bcmath, curl, dba, dom, enchant, fileinfo, gd, imagick, imap, intl, json, ldap, mapi, exif, mcrypt, mysqli, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, redis, soap, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlrpc, xmlwriter, xsl, zip, ionCube Loader, Zend OPcache

**Nextcloud version:** 13.0.0 RC 1 - 13.0.0.10

**Updated from an older Nextcloud/ownCloud or fresh install:** 
Updated from 12.0.5 beta

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Integrity checker has been disabled. Integrity cannot be verified.
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_audit: 1.3.0
 - admin_notifications: 1.0.1
 - announcementcenter: 3.1.1
 - audioplayer: 2.2.2
 - bookmarks: 0.10.1
 - bruteforcesettings: 1.0.3
 - calendar: 1.5.7
 - checksum: 0.3.5
 - circles: 0.13.6
 - comments: 1.3.0
 - contacts: 2.0.1
 - dashboard: 4.0.5
 - dav: 1.4.6
 - deck: 0.3.0
 - documents: 0.16.0
 - external: 3.0.1
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_accesscontrol: 1.3.0
 - files_automatedtagging: 1.3.0
 - files_clipboard: 0.6.5
 - files_downloadactivity: 1.2.0
 - files_external: 1.4.1
 - files_gpxviewer_extended: 1.5
 - files_markdown: 2.0.1
 - files_pdfviewer: 1.2.0
 - files_reader: 1.0.4
 - files_retention: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - files_videoviewerplus: 0.2.0
 - firstrunwizard: 2.2.1
 - flowupload: 0.0.5
 - gallery: 18.0.0
 - gpxedit: 0.0.7
 - gpxmotion: 0.0.5
 - gpxpod: 2.2.2
 - groupfolders: 1.1.0
 - impersonate: 1.0.2
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - metadata: 0.6.0
 - music: 0.5.5
 - nextcloud_announcements: 1.2.0
 - notes: 2.3.2
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - ojsxc: 3.3.2
 - ownnote: 1.08
 - password_policy: 1.3.0
 - previewgenerator: 1.0.9
 - provisioning_api: 1.3.0
 - quota_warning: 1.2.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - spreed: 3.0.1
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - tasks: 0.9.5
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - user_external: 0.4
 - workflowengine: 1.3.0
Disabled:
 - encryption
 - files_inotify
 - folderplayer
 - html5_videoplayer
 - socialsharing_googleplus
 - user_ldap
 - drawio

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "user_backends": [
        {
            "class": "OC_User_IMAP",
            "arguments": [
                "***REMOVED SENSITIVE VALUE***",
                ""
            ]
        }
    ],
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "auth.bruteforce.protection.enabled": true,
    "session_lifetime": 600,
    "session_keepalive": true,
    "dbtype": "pgsql",
    "version": "13.0.0.10",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "htaccess.RewriteBase": "\/",
    "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
    "htaccess.IgnoreFrontController": false,
    "loglevel": 3,
    "log_rotate_size": true,
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "theme": "",
    "updatechecker": true,
    "has_internet_connection": true,
    "check_for_working_htaccess": true,
    "check_for_working_webdav": true,
    "integrity.check.disabled": true,
    "appcodechecker": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "filelocking.enabled": "true",
    "memcache.locking": "\\OC\\Memcache\\APCu",
    "trashbin_retention_obligation": "auto",
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\SVG",
        "OC\\Preview\\TIFF",
        "OC\\Preview\\Font"
    ],
    "appstoreenabled": true,
    "appstore.experimental.enabled": true,
    "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
    "updater.release.channel": "beta",
    "data-fingerprint": "af0a0d094bdebcec3c8c275602d04705",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** 
local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** 
OC_User_IMAP

</details>

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Operating system:** 

## Logs

<details><summary>Browser log</summary>

```
```
</details>

<details><summary>Nextcloud log</summary>

```
Failed sending activity email to user "sepp": {"Exception":"Swift_RfcComplianceException","Message":"Address in mailbox given [josef.katzlschinder@] does not comply with RFC 2822, 3.6.2.","Code":0,"Trace":"#0 \/var/www/nc\/3rdparty\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Mime\/Headers\/MailboxHeader.php(261): Swift_Mime_Headers_MailboxHeader->_assertValidAddress('josef.katzlschind...')\n#1 \/var/www/nc\/3rdparty\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Mime\/Headers\/MailboxHeader.php(106): Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(Array)\n#2 \/var/www/nc\/3rdparty\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Mime\/Headers\/MailboxHeader.php(63): Swift_Mime_Headers_MailboxHeader->setNameAddresses(Array)\n#3 \/var/www/nc\/3rdparty\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Mime\/SimpleHeaderFactory.php(58): Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(Array)\n#4 \/var/www/nc\/3rdparty\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Mime\/SimpleHeaderSet.php(68): Swift_Mime_SimpleHeaderFactory->createMailboxHeader('To', Array)\n#5 \/var/www/nc\/3rdparty\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Mime\/SimpleMessage.php(329): Swift_Mime_SimpleHeaderSet->addMailboxHeader('To', Array)\n#6 \/var/www/nc\/lib\/private\/Mail\/Message.php(144): Swift_Mime_SimpleMessage->setTo(Array)\n#7 \/var/www/nc\/apps\/activity\/lib\/MailQueueHandler.php(409): OC\\Mail\\Message->setTo(Array)\n#8 \/var/www/nc\/apps\/activity\/lib\/MailQueueHandler.php(183): OCA\\Activity\\MailQueueHandler->sendEmailToUser('sepp', 'josef.katzlschind...', 'de', 'Europe\/Berlin', 1515774601)\n#9 \/var/www/nc\/apps\/activity\/lib\/BackgroundJob\/EmailNotification.php(65): OCA\\Activity\\MailQueueHandler->sendEmails(500, 1515774601)\n#10 \/var/www/nc\/lib\/private\/BackgroundJob\/Job.php(61): OCA\\Activity\\BackgroundJob\\EmailNotification->run(NULL)\n#11 \/var/www/nc\/lib\/private\/BackgroundJob\/TimedJob.php(55): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#12 \/var/www/nc\/cron.php(123): OC\\BackgroundJob\\TimedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#13 {main}","File":"\/var/www/nc\/3rdparty\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Mime\/Headers\/MailboxHeader.php","Line":345}
idn_to_ascii() expects parameter 3 to be integer, string given at /var/www/nc/lib/private/Mail/Message.php#77
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by nickvergessen** [comment]
Your email adress is missing the domain?

**Comment by nickvergessen** [comment]
The activity app does not perform any magic on the emails.
I could imagine that an update of the user_external app which you seem to be using caused this.

**Comment by umgfoin** [comment]
Hi Joas,
cause identified - problems with import from intl-lib
The IDN-conditioner uses undefined `INTL_IDNA_VARIANT_UTS46` in Mailer.php and Mail.php.
e.g.
` $domain = idn_to_ascii($domain, 0, INTL_IDNA_VARIANT_UTS46);`

If I replace the constant by its int (1) representation, same thing happens.
The function returns useful values only if variant ` INTL_IDNA_VARIANT_2003` is used.
```php[sepp@cloud Mail]# php7 -a
Interactive shell
php > echo idn_to_ascii("nextcloud.com", 0, INTL_IDNA_VARIANT_UTS46);
PHP Notice:  Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed INTL_IDNA_VARIANT_UTS46' in php shell code on line 1
PHP Warning:  idn_to_ascii() expects parameter 3 to be integer, string given in php shell code on line 1
php > echo idn_to_ascii("nextcloud.com", 0, 1);
php > echo idn_to_ascii("nextcloud.com", 0, INTL_IDNA_VARIANT_2003 );
nextcloud.com
php > echo idn_to_ascii("nextcloud.com", 0, 0);
nextcloud.com
php > 
```
++umgfoin.

**Comment by nickvergessen** [comment]
UTS46 was introduced with php 5.4 so it should work well.
Otherwise make sure you have php-intl installed.

But glad that it is not caused by the activity app.

**Comment by umgfoin** [comment]
> UTS46 was introduced with php 5.4 so it should work well.

Correct.
I'm on php 7.1 and php-intl is installed.
The problem seems to be buried in intl's dependency on libicu:
UTS46 is available in icu >=4.6, CentOS is on 4.2
Obviously it's possible to build php-intl 7.1 against elder libicu not supporting UTS46.

I personally will be able to fix this, but maybe it's better advice to not only check (in Mail.php etc.) for existance of function `idn_to_ascii`, but also for declaration of `INTL_IDNA_VARIANT_UTS46` before trying to do idn-conversion.

**Comment by BandonRandon** [comment]
> I personally will be able to fix this,
@umgfoin any tips for how to compile and upgrade icu on CentOS 6.9 to one which supports `UTS46` ? Dosen't seem to be a lot of this online.

**Comment by nickvergessen** [comment]
Well the thing is, if we try to check for all constants before we use them, it will be a much more complicated.
Of course adding a single check for a single usage sounds okay. But in the end you end up with 100 checks for 100 constants.
