### ISSUE TITLE
No mail for file activity

### ISSUE THREAD

**Issue by ad1rie1** [nextcloud/activity#255]
Hello, i have no mail for file activity at all, but it's working fine for calendar event.
I use Cron to shedule Task

### Steps to reproduce
1. Set send mail on file added, enable mail notification and set to 15 min to user 1
2. Share folder with other users 2
3. The user 2  add file to share of user1

### Expected behaviour
One mail is send to the user 1 to recap files added

### Actual behaviour
Nothing append

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:**  Apache/2.4.18 (Ubuntu)

**Database:** 10.0.34-MariaDB-0ubuntu0.16.04.1

**PHP version:** PHP 7.0.25-0ubuntu0.16.04.1

**Nextcloud version:** 13.0

**Where did you install Nextcloud from:** Stable

```
No errors have been found.
```

**List of activated apps:**

```
root@NEXTCLOUD:/var/www/html# sudo -u www-data php occ app:list
Enabled:
  - activity: 2.6.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.2
  - dav: 1.4.6
  - deck: 0.3.1
  - drawio: 0.8.9
  - external: 3.0.2
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_automatedtagging: 1.3.0
  - files_pdfviewer: 1.2.0
  - files_retention: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - unsplash: 1.0.6
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - gallery
  - spreed
  - user_external
  - user_ldap

```

**Nextcloud configuration:**

```
root@NEXTCLOUD:/var/www/html# sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "172.17.0.10",
            "nextcloud.brain-networks.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/172.17.0.10",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "activity_expire_days": 30,
        "loglevel": 4
    }
}

```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No  i have no LDAP or external storage
### Client configuration
**Browser:** 
Google chrome 65.0.3325.162

**Operating system:** 
WIndows 10

#### Nextcloud log (data/nextcloud.log)
```
root@NEXTCLOUD:/var/www/html# cat /var/www/html/data/nextcloud.log
{"reqId":"cS6dda36JsihTn14lQvG","level":3,"time":"2017-11-17T07:38:59+00:00","remoteAddr":"10.242.2.2","user":"--","app":"PHP","method":"POST","url":"\/index.php","message":"file_get_contents(\/var\/www\/html\/.htaccess): failed to open stream: No such file or directory at \/var\/www\/html\/lib\/private\/Setup.php#446","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/62.0.3202.94 Safari\/537.36","version":"12.0.3.3"}
{"reqId":"cS6dda36JsihTn14lQvG","level":3,"time":"2017-11-17T07:39:04+00:00","remoteAddr":"10.242.2.2","user":"admin-brain","app":"PHP","method":"POST","url":"\/index.php","message":"copy(\/var\/www\/html\/.user.ini): failed to open stream: No such file or directory at \/var\/www\/html\/lib\/private\/IntegrityCheck\/Checker.php#192","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/62.0.3202.94 Safari\/537.36","version":"12.0.3.3"}
{"reqId":"cS6dda36JsihTn14lQvG","level":2,"time":"2017-11-17T07:39:04+00:00","remoteAddr":"10.242.2.2","user":"admin-brain","app":"files","method":"POST","url":"\/index.php","message":"Can't write upload limit to \/tmp\/oc_tmp_5O304s-folder\/.user.ini. Please check the file permissions","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/62.0.3202.94 Safari\/537.36","version":"12.0.3.3"}
{"reqId":"vlJSaMyP5njgPmIFRtuw","level":3,"time":"2018-02-20T10:22:52+00:00","remoteAddr":"172.17.0.1","user":"--","app":"PHP","method":"PROPFIND","url":"\/remote.php\/webdav\/","message":"touch(): Utime failed: Permission denied at \/var\/www\/html\/lib\/private\/Config.php#239","userAgent":"--","version":""}
{"reqId":"vlJSaMyP5njgPmIFRtuw","level":3,"time":"2018-02-20T10:22:52+00:00","remoteAddr":"172.17.0.1","user":"--","app":"PHP","method":"PROPFIND","url":"\/remote.php\/webdav\/","message":"fopen(\/var\/www\/html\/config\/config.php): failed to open stream: Permission denied at \/var\/www\/html\/lib\/private\/Config.php#240","userAgent":"--","version":""}
{"reqId":"vlJSaMyP5njgPmIFRtuw","level":3,"time":"2018-02-20T10:22:52+00:00","remoteAddr":"172.17.0.1","user":"--","app":"PHP","method":"PROPFIND","url":"\/remote.php\/webdav\/","message":"chmod(): Operation not permitted at \/var\/www\/html\/lib\/private\/Config.php#243","userAgent":"--","version":""}
{"reqId":"vlJSaMyP5njgPmIFRtuw","level":3,"time":"2018-02-20T10:22:52+00:00","remoteAddr":"172.17.0.1","user":"--","app":"remote","method":"PROPFIND","url":"\/remote.php\/webdav\/","message":"Exception: {\"Exception\":\"OC\\\\HintException\",\"Message\":\"Can't write into config directory!\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Config.php(131): OC\\\\Config->writeData()\\n#1 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/SystemConfig.php(90): OC\\\\Config->setValue('instanceid', 'ocq9uyd0wcwd')\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/legacy\\\/util.php(1128): OC\\\\SystemConfig->setValue('instanceid', 'ocq9uyd0wcwd')\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(420): OC_Util::getInstanceId()\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(675): OC::initSession()\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(1086): OC::init()\\n#6 \\\/var\\\/www\\\/html\\\/remote.php(110): require_once('\\\/var\\\/www\\\/html\\\/l...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Config.php\",\"Line\":250}","userAgent":"--","version":""}
```

**Comment by nickvergessen** [comment]
Duplicate #244

**Comment by ad1rie1** [comment]
Thanck you :)
